var keyMirror = require('keymirror');

module.exports = keyMirror({
  GET_ALL_DEPLOYMENTS: null,
  GET_DEPLOYMENT_AS_BLUEPRINT_FOR_DELETION: null,
  GET_DEPLOYMENT_AS_BLUEPRINT: null,
  DELETE_FULL_DEPLOYMENT: null,
  GET_DEPLOYMENT: null,
  CLEANUP_DEPLOYMENT: null,
  GET_DEPLOYMENT_METRICS_SCUR: null,
  GET_DEPLOYMENT_METRICS_RTIME: null,
  UPDATE_DEPLOYMENT_ROUTING: null
});